### ISSUE TITLE
These are some bugs in version 10.6.6

### ISSUE THREAD

**Issue by stackcats** [kataras/iris#1029]
go version go1.10.1 darwin/amd64

vendor/github.com/kataras/survey/confirm.go:53:30: cannot use os.Stdin (type *os.File) as type terminal.Stdio in argument to terminal.NewRuneReader
vendor/github.com/kataras/survey/confirm.go:63:3: undefined: terminal.CursorPreviousLine
vendor/github.com/kataras/survey/editor.go:82:30: cannot use os.Stdin (type *os.File) as type terminal.Stdio in argument to terminal.NewRuneReader
vendor/github.com/kataras/survey/editor.go:86:2: undefined: terminal.CursorHide
vendor/github.com/kataras/survey/editor.go:87:8: undefined: terminal.CursorShow
vendor/github.com/kataras/survey/editor.go:141:2: undefined: terminal.CursorShow
vendor/github.com/kataras/survey/input.go:56:30: cannot use os.Stdin (type *os.File) as type terminal.Stdio in argument to terminal.NewRuneReader
vendor/github.com/kataras/survey/input.go:68:3: undefined: terminal.CursorPreviousLine
vendor/github.com/kataras/survey/multiselect.go:140:2: undefined: terminal.CursorHide
vendor/github.com/kataras/survey/multiselect.go:142:8: undefined: terminal.CursorShow
vendor/github.com/kataras/survey/multiselect.go:142:8: too many errors

**Comment by kataras** [comment]
These are not bugs, something is missing from your dependencies about kataras/survey which is used on https://github.com/kataras/iris/blob/master/core/maintenance/version.go#L43

**Comment by kataras** [comment]
I've just re-installed Go and made a fresh install of Iris on a windows remote server machine I have for testing and it's working fine, tell me if you need any help.

![freshinstall](https://user-images.githubusercontent.com/22900943/41818379-5d836718-77b6-11e8-8be6-e052e5fdffb0.png)

**Comment by stackcats** [comment]
I use dep for dependencies
It works with iris version 10.0.0
but can not work with iris version 10.6.6

dep:
 version     : v0.4.1
 build date  : 2018-01-27
 git hash    : 37d9ea0
 go version  : go1.9.3
 go compiler : gc
 platform    : darwin/amd64

**Comment by kataras** [comment]
Yeap, looks like this: https://github.com/kataras/iris/issues/1025 and more, all solved and they are caused because of third-party tools like `gb vendor` and `dep` I am NOT recommending using these type of tools for managing your dependencies and like I see the last month I was NOT the only one, Russ also did :)

**Comment by kataras** [comment]
Iris is fully vendored, don't worry, at least for your Iris dependency.

**Comment by kataras** [comment]
@stackcats  see https://github.com/kataras/iris/issues/1030#issuecomment-399810957 as well.

**Comment by Toyz** [comment]
I found a very simple fix in VSCode find the string `gopkg.in/AlecAivazis/survey.v1` and replace it with `gopkg.in/AlecAivazis/survey.v1` this will fix the bug, but make sure you push vendor to your repo

**Comment by kataras** [comment]
You aren't talking about Iris because the string `gopkg.in/AlecAivazis/survey.v1` is not there, nothing uses it from our side, maybe you use another project which defines that and your external dep manager confused it with the `kataras/survey` for some reason?

**Comment by Toyz** [comment]
For what ever reason when you use dep to get the iris package it changes the survey package imports to use those instead of surveys own, replacing the strings like that is what fixes the problem after using dep, not related to the repo

Sent from my iPhone

On Jun 25, 2018, at 12:44 PM, Gerasimos (Makis) Maropoulos <notifications@github.com<mailto:notifications@github.com>> wrote:


You aren't talking about Iris because the string gopkg.in/AlecAivazis/survey.v1<http://gopkg.in/AlecAivazis/survey.v1> is not there, nothing uses it from our side, maybe you use another project which defines that and your external dep manager confused it with the kataras/survey for some reason?

**Comment by kataras** [comment]
Thank you for the clarification because you scared the sh..t out of me!

**Comment by Toyz** [comment]
Not a problem

Sent from my iPhone

On Jun 25, 2018, at 7:14 PM, Gerasimos (Makis) Maropoulos <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for the clarification because you scared the sh..t out of me!

**Comment by ninisnanas** [comment]
Is it possible because kataras/survey is forked from AlecAivazis:master and is behind the master so Dep assumes that the import is invalid so it tries to get the latest code?

**Comment by bilfash** [comment]
I think @ninisnanas were right, I am facing the same issue, and my solution is changing every import from "gopkg.in/AlecAivazis/survey.v1" to "github.com/kataras/survey".

**Comment by kataras** [comment]
But we don't have `gopkg.in/AlecAivazis/survey.v1` how the hell the dependency manager thinks that it's the same repo instead of an imporvement *fork*? This is a serious `dep`'s bug that can ruine thousands of projects and you should post it there, although as I said *do not use dependency managers yet, go is not ready for that yet*.

**Comment by kataras** [comment]
So the solution is to make a "duplicate" repository each time I want to edit a library that X project uses? This is bullshit, `dep` has failed, do NOT use that.

**Comment by kataras** [comment]
@ninisnanas , @Toyz @bilfash could you please re-try? I added the `kataras/survey` to the iris' `Gopkg.toml` file (which  I created manually for dep users, although I don't use it at all but may be useful for you)

**Comment by stackcats** [comment]
It works now

iris version 10.6.6

**Comment by kataras** [comment]
That's wonderful, we helped each other here, thank you for your contribution  awesome iris developers!

**Comment by bilfash** [comment]
awesome :)
