### ISSUE TITLE
[Question]How can i get en error if frontend post an empty value or empty form 

### ISSUE THREAD

**Issue by Boreals** [kataras/iris#1625]
```go
package main

import "github.com/kataras/iris/v12"

type loginForm struct {
	Username string `form:"username" validate:"required"`
	Password string `form:"password" validate:"required"`
}
func main()  {
	app := iris.Default()
	app.Post("/", func(context iris.Context){
		var loginParams loginForm
		err := context.ReadForm(&loginParams)
		if err!=nil {
			context.JSON(iris.Map{
				"Code":"400",
				"Msg":err.Error(),
			})
			return
		}
		context.JSON(iris.Map{
			"Code":"200",
			"Msg":loginParams,
		})
	})
	app.Listen(":8090")
}
```

I have used required validator ,but i used Postman and then post this address with nothing ,i get the following result,is there something wrong? 
```json
{
    "Code": "200",
    "Msg": {
        "Username": "",
        "Password": ""
    }
}
```

**Comment by kataras** [comment]
Yes @Boreals, I see that you forgot to pass the `WithEmptyFormError` in your `app.Listen`. If that exists then an `iris.ErrEmptyForm` returns on `ReadForm` if the form payload is empty.

Example: 

https://github.com/kataras/iris/blob/c4843a4d82aae53518bb7c247923007d1d99893c/_examples/request-body/read-form/main.go#L32-L46

**Comment by Boreals** [comment]
```go 
func DefaultConfiguration() Configuration {
	return Configuration{
		DisableStartupLog:                 false,
		DisableInterruptHandler:           false,
		DisablePathCorrection:             false,
		EnablePathEscape:                  false,
		FireMethodNotAllowed:              false,
		DisableBodyConsumptionOnUnmarshal: false,
		DisableAutoFireStatusCode:         false,
		TimeFormat:                        "Mon, 02 Jan 2006 15:04:05 GMT",
		Charset:                           "UTF-8",

		// PostMaxMemory is for post body max memory.
		//
		// The request body the size limit
		// can be set by the middleware `LimitRequestBodySize`
		// or `context#SetMaxRequestBodySize`.
		PostMaxMemory:        32 << 20, // 32MB
		LocaleContextKey:     "iris.locale",
		ViewLayoutContextKey: "iris.viewLayout",
		ViewDataContextKey:   "iris.viewData",
		RemoteAddrHeaders:    make(map[string]bool),
		EnableOptimizations:  false,
		Other:                make(map[string]interface{}),
	}
}
```
undefined: iris.WithEmptyFormError
My iris is V12.1.8

**Comment by Boreals** [comment]
I found that configuration.go has `FireEmptyFormError` ,i'll try update

**Comment by Boreals** [comment]
When i update to V12.1.9,i get the `empty form`

**Comment by kataras** [comment]
Yes @Boreals this is the `master/development` version. It's not tagged yet.

**Comment by hjzCy** [comment]
@kataras 
The same problem is true for get requests, and no error will be triggered when the url parameter is not passed. How should I configure it?

```go
app := iris.New()
app.Validator = validator.New()

// MVC
func (c *ApiController) GetFinanceTest(p struct {
    PayIds      string `url:"pay_ids" validate:"required"`    
    AccId       int    `url:"acc_id" validate:"required,min=1"`
}) {
    // If an error occurs normally, it should not be executed here, but it passed
    fmt.Println(p.AccId) // = 0
}
```

// _ = app.Listen(":8080")
app.Listen(":8080", iris.WithEmptyFormError) // ?
