### ISSUE TITLE
[BUG] install iris failed

### ISSUE THREAD

**Issue by bali2016** [kataras/iris#1421]
```
# go get -u github.com/kataras/iris
# github.com/kataras/iris/context
/root/go/src/github.com/kataras/iris/context/context.go:2893:6: undefined: errors.Is
# github.com/kataras/iris/core/errgroup
/root/go/src/github.com/kataras/iris/core/errgroup/errgroup.go:109:9: undefined: errors.Unwrap
/root/go/src/github.com/kataras/iris/core/errgroup/errgroup.go:118:8: undefined: errors.Is
/root/go/src/github.com/kataras/iris/core/errgroup/errgroup.go:125:10: undefined: errors.Is
/root/go/src/github.com/kataras/iris/core/errgroup/errgroup.go:137:8: undefined: errors.As
/root/go/src/github.com/kataras/iris/core/errgroup/errgroup.go:150:10: undefined: errors.As
```

```
# go version
go version go1.12.7 linux/amd64
```

**Comment by bali2016** [comment]
After upgrade the go to v1.13, get new error:

```
# go version
go version go1.13.5 linux/amd64
root@CDN-Shanghai-Bali-002:~# go get -u github.com/kataras/iris
# github.com/kataras/iris/view
go/src/github.com/kataras/iris/view/jet.go:375:2: cannot use interface {} value as type reflect.Value in return argument: need type assertion
```

**Comment by XiaoMuIns** [comment]
me too,,
![image](https://user-images.githubusercontent.com/24638429/71777689-33693700-2fde-11ea-9df6-d542cb3b4184.png)

![image](https://user-images.githubusercontent.com/24638429/71777702-42e88000-2fde-11ea-8bcd-1f41ce4af285.png)

**Comment by kataras** [comment]
@bali2016  and @XiaoMuIns

Please read the [installation section](https://github.com/kataras/iris/wiki/Installation#install) before opening an issue like this. The command to install Iris is: `go get github.com/kataras/iris/v12@latest`.

> Relative: https://github.com/kataras/iris/issues/1420#issuecomment-570831572
