### ISSUE TITLE
Directory structure of packages have be changed but do not update it in _examples code

### ISSUE THREAD

**Issue by zuoxiaofeng** [kataras/iris#769]
Directory structure of packages have be changed but do not update it in _examples code(such as Context, SessionController) , It is unfriendly to newers.

Thanks.

**Comment by hiveminded** [comment]
Dear @zuoxiaofeng , 
There are not any changes to the "directory structure".

- Could you explain what is "unfriendly to newers" about _examples?  
- What's wrong with the SessionController and Context examples? 
- Could you provide us some examples in order to understand what you want to report here?

**Comment by zuoxiaofeng** [comment]
This is the code in "_examples\mvc\login\user\auth.go(line 24-29)"
type AuthController struct {
	iris.SessionController

	Source *DataSource
	User   Model `iris:"model"`
}
when build the login example will failed with the error:
      "user\auth.go:24: undefined: iris.SessionController"
I found the SessionController is under mvc now, the iris.SessionController should be mvc.SessionController, and also need import "github.com/kataras/iris/mvc"

The Context was move to context onw and the iris.Context should be context.Context I think.
This is the code in "_examples\mvc\login\user\auth.go(line 119-125)"
func AllowUser(ctx iris.Context) {
	if ctx.Values().Get(sessionIDKey) != nil {
		ctx.Next()
		return
	}
	ctx.Redirect(PathLogin)
}

**Comment by zuoxiaofeng** [comment]
Also the example in readme.md can not build succeed too.（caused by "iris.Context" ）

**Comment by hiveminded** [comment]
@zuoxiaofeng You see? you don't read the README and you open a new issue, this is not right... let me explain one more time; these "problems" are caused because you try to build using Go version 1.8, `iris.Context, iris.Controller` are **type aliases** and can be used instead of `context.Context and mvc.Controller` in **Go Version 1.9**.

 Below the README example is your answer, take a look at the https://github.com/kataras/iris#-installation `Hello World with Go 1.8`, click that dropdown and you'll see all available type alias for Go 1.9: https://github.com/kataras/iris/blob/master/context.go . Examples are working with the latest go version **go 1.9**, as always. If you use Go 1.8 you have to read the last link and see the import statements.

**Comment by hiveminded** [comment]
I've just write a new whole section which you can look to see the original import statements and their type aliases, **read** https://github.com/kataras/iris#-type-aliases, have a wonderful day!

**Comment by zuoxiaofeng** [comment]
@hiveminded Thank you first, and you are right, my go version is 1.8, I have run the example for 1.9 on go 1.8. I do not know about the new features of go 1.9, I will continue to learn it.
Thank you.
